//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TB_CATEGORY")]
    public partial class TB_CATEGORY
    {
        public TB_CATEGORY()
        {
            this.TB_SUBCATEGORY = new HashSet<TB_SUBCATEGORY>();
        }

        [Key]
        [Display(Name = "ID ")]
        public int ID_CATEGORY { get; set; }
        [Required]
        [Display(Name = "Categoria ")]
        public string DESCRIPTION { get; set; }

        public virtual ICollection<TB_SUBCATEGORY> TB_SUBCATEGORY { get; set; }
    }
}
