//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TB_GROUP")]
    public partial class TB_GROUP
    {
        public TB_GROUP()
        {
            this.TB_GROUP_USER = new HashSet<TB_GROUP_USER>();
        }

        [Key]
        [Display(Name = "ID ")]
        public int ID_GROUP { get; set; }
        [Required]
        [Display(Name = "Nome ")]
        public string GROUP_NAME { get; set; }
        [Display(Name = "Descrição ")]
        public string GROUP_DESCRIPTION { get; set; }

        public virtual ICollection<TB_GROUP_USER> TB_GROUP_USER { get; set; }
    }
}
