//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TB_GROUP_USER")]
    public partial class TB_GROUP_USER
    {
        [Key]
        [Display(Name = "ID ")]
        public int ID_GROUP_USER { get; set; }
        [Required]
        [Display(Name = "Usuário ")]
        public int ID_USER { get; set; }
        [Required]
        [Display(Name = "Grupo ")]
        public int ID_GROUP { get; set; }
        [Display(Name = "OBS ")]
        public string OBS { get; set; }

        [Display(Name = "Grupo ")]
        public virtual TB_GROUP TB_GROUP { get; set; }
        [Display(Name = "Usuário ")]
        public virtual TB_USER TB_USER { get; set; }
    }
}
