//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TB_PRODUCT")]
    public partial class TB_PRODUCT
    {
        [Key]
        [Display(Name = "ID ")]
        public int ID_PRODUCT { get; set; }
        [Required]
        [Display(Name = "SubCategoria ")]
        public int ID_SUBCATEGORY { get; set; }
        [Required]
        [Display(Name = "Descrição ")]
        public string DESCRIPTION { get; set; }
        [Display(Name = "Usuário ")]
        public int ID_USER { get; set; }

        [Display(Name = "SubCategoria ")]
        public virtual TB_SUBCATEGORY TB_SUBCATEGORY { get; set; }
    }
}
