//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    [Table("TB_USER")]
    public partial class TB_USER
    {
        public TB_USER()
        {
            this.TB_GROUP_USER = new HashSet<TB_GROUP_USER>();
        }

        [Key]
        [Display(Name = "ID ")]
        public int ID_USER { get; set; }
        [Required]
        [Display(Name = "Login ")]
        public string LOGIN { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha ")]
        public string PASSWD { get; set; }

        [Display(Name = "Nome ")]
        public string USER_NAME { get; set; }
        public string PASSWSALT { get; set; }

        public virtual ICollection<TB_GROUP_USER> TB_GROUP_USER { get; set; }
    }

    public partial class UserPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Senha atual")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "A senha {0} deve ter pelo menos {2} caracteres.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Nova senha")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirmar senha")]
        [Compare("NewPassword", ErrorMessage = "A nova senha e a confirmação não correspondem")]
        public string ConfirmPassword { get; set; }
    }
}
